name: sandbox
dependencies:
- python=3.6
- jupyter=1.0.0
- matplotlib=2.2.2
- pandas=0.23.2
- tensorflow=1.12
- pip:
  - requests==2.18.4
  - mxnet==1.3.0
  - gluonbook==0.8.3
  - gluoncv==0.3.0
  - mxboard==0.1.0
